openapi: 3.1.0

info:
  title: Whispr API Design
  description:
    A comprehensive REST API for a real-time chat application supporting user management,
    conversations, messaging, and real-time notifications.
  version: 1.0.0
  license:
    name: MIT License
    url: https://opensource.org/license/mit/

servers:
  - url: 'https://api.whispr.com'
    description: Production server

paths:
  /api/v1/profile/{id}:
    get:
      summary: Get User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to retrieve

  /api/v1/profile/me:
    get:
      summary: Get Current User

  /api/v1/profile/me/details:
    get:
      summary: Get Current User Details




